### ISSUE TITLE
riscv-pk has error

### ISSUE THREAD

**Issue by mperov** [janvrany/riscv-debian#12]
When I run script - `./debian-mk-kernel.mk` I faced with error:
```
riscv64-linux-gnu-gcc -MMD -MP -Wall -Werror -D__NO_INLINE__ -mcmodel=medany -O2 -std=gnu99 -Wno-unused -Wno-attributes -fno-delete-null-pointer-checks -fno-PIE    -DBBL_PAYLOAD=\"bbl_payload\" -DBBL_LOGO_FILE=\"bbl_logo_file\" -I. -I../pk -I../bbl -I../softfloat -I../dummy_payload -I../machine -I../util -c ../pk/pk.c
../pk/pk.c: In function 'rest_of_boot_loader':
../pk/pk.c:139:3: error: both arguments to '__builtin___clear_cache' must be pointers
  139 |   __clear_cache(0, 0);
      |   ^~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:319: pk.o] Error 1
make[1]: Leaving directory '/home/coder/work/linuxPorting/riscv-debian/riscv-pk/build'
make: *** [debian-mk-kernel.mk:27: bbl-q] Error 2
```
I found that this issue was fixed - https://github.com/riscv-software-src/riscv-pk/issues/239
So I think to resolve it you should update submodule riscv-pk.

**Comment by janvrany** [comment]
Thanks! 

Have you tried to update it? If so and if it works, just open the PR. 

If not, I might have a look later, but honestly this is not a top priority since - AFAIK - BBL is obsolete in favour of OpenSBI and U-boot, see branches

* https://github.com/janvrany/riscv-debian/tree/linux-5.0
* https://github.com/janvrany/riscv-debian/tree/linux-5.6

These might be a better start with if you just need to get going somehow. 
I should make OpenSBI + Linux 5.x the default 'master' branch - the reason of not doing so is long time gone.

**Comment by mperov** [comment]
@janvrany I will try to update today!

**Comment by mperov** [comment]
Hi @janvrany I tried to update and it helped to fix this error. Now I'd like to run kernel on QEMU
